apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: smb-vol-1
    volumeAttributes:
      source: //192.168.68.24/docs
    nodeStageSecretRef:
      name: smbcreds
      namespace: default
